import type { ServiceConfig } from "./types";
import {
  ElementPlusSizeEnum,
  HeaderMenuAlignEnum,
  HeaderStyleEnum,
  LanguageEnum,
  LayoutModeEnum,
  MenuThemeEnum,
  PageTransitionEnum,
  GlobalThemeEnum,
  TabNavElementModeEnum,
  ThemePanelTriggerPositionEnum,
  TitleModeEnum,
  MenuShowModeEnum,
  HeaderShowModeEnum,
  MenuStyleEnum,
  ThemeSurfaceEnum,
} from "../service-enum";

export const defaultServiceConfig: ServiceConfig = {
  layout: {
    name: "Teek Design Vue3",
    avatar: "/avatar.png",
    titleMode: TitleModeEnum.ProjectPage,
    layoutMode: LayoutModeEnum.Vertical,
    maximize: false,
    watermark: false,
    moreRouteChildrenHideInMenuThenOnlyOne: false,
    tooltipEffect: isDark => (isDark ? "light" : "dark"),
    elementPlusSize: ElementPlusSizeEnum.Default,
    language: LanguageEnum.ZhCn,
    watchFrame: false,
    lockSecretKey: "my-secret-key",
    errorLog: {
      showInHeader: true,
      printConsole: true,
      env: [],
    },
    themePanelTriggerPosition: ThemePanelTriggerPositionEnum.Header,
    globalAlert: {
      enabled: false,
      text: "Teek Design Vue3 祝您圣诞快乐，愿节日的欢乐与祝福如雪花般纷至沓来！",
      startDate: "2025-12-25",
      endDate: "2025-12-25",
      type: "primary",
      closable: true,
      showIcon: false,
    },
  },
  theme: {
    // 默认与 css var 一致，在这里配置一份，方便生成 1 - 9 的基础色
    primaryColor: "#395ae3",
    successColor: "#0b9e40",
    warningColor: "#e68a00",
    dangerColor: "#d93126",
    errorColor: "#dd5c27",
    infoColor: "#5c667a",
    globalThemeMode: GlobalThemeEnum.System,
    radius: 0.75,
    weakMode: false,
    greyMode: false,
    presetsColor: [
      "#dc2626",
      "#ef4444",
      "#f87171",
      "#fca5a5",
      "#b91c1c",
      "#991b1b",
      "#7f1d1d",
      "#e11d48",
      "#be123c",
      "#9f1239",
      "#ea580c",
      "#f97316",
      "#fb923c",
      "#fdba74",
      "#c2410c",
      "#9a3412",
      "#7c2d12",
      "#d97706",
      "#b45309",
      "#eab308",
      "#fbbf24",
      "#facc15",
      "#fde047",
      "#fef3c7",
      "#16a34a",
      "#22c55e",
      "#4ade80",
      "#86efac",
      "#15803d",
      "#166534",
      "#14532d",
      "#059669",
      "#10b981",
      "#34d399",
      "#0d9488",
      "#14b8a6",
      "#2dd4bf",
      "#5eead4",
      "#0f766e",
      "#115e59",
      "#134e4a",
      "#06b6d4",
      "#22d3ee",
      "#67e8f9",
      "#2563eb",
      "#3b82f6",
      "#60a5fa",
      "#93c5fd",
      "#1d4ed8",
      "#1e40af",
      "#1e3a8a",
      "#6366f1",
      "#8b5cf6",
      "#a855f7",
      "#0ea5e9",
      "#38bdf8",
      "#7dd3fc",
      "#4f46e5",
      "#4338ca",
      "#7c3aed",
      "#8b5cf6",
      "#a78bfa",
      "#c4b5fd",
      "#6d28d9",
      "#5b21b6",
      "#4c1d95",
      "#9333ea",
      "#c026d3",
      "#db2777",
      "#6b7280",
      "#9ca3af",
      "#d1d5db",
      "#e5e7eb",
      "#f3f4f6",
      "#374151",
      "#1f2937",
      "#111827",
      "#000000",
      "#ffffff",
    ],
    surface: ThemeSurfaceEnum.TeekBrand,
    functionalColorStrictly: true,
  },
  header: {
    enabled: true,
    height: 55,
    style: HeaderStyleEnum.Page,
    menuAlign: HeaderMenuAlignEnum.Start,
    showMode: HeaderShowModeEnum.Fixed,
  },
  menu: {
    enabled: true,
    width: 240,
    accordion: false,
    collapsed: false,
    collapseWidth: 64,
    theme: MenuThemeEnum.Light,
    style: MenuStyleEnum.Simple,
    showMode: MenuShowModeEnum.Static,
    autoActivateChild: true,
    showModeAutoFixed: true,
    rightClickMenuCollapseToClose: true,
  },
  tabNav: {
    enabled: true,
    elementMode: TabNavElementModeEnum.Simple,
    showIcon: true,
    showDot: true,
    persistence: false,
    fixed: true,
    draggable: true,
    height: 38,
    middleClickToClose: false,
    middleClickToOpen: false,
    middleClickToOpenInNewWindow: true,
    showMore: true,
    wheel: true,
    maxCount: 0,
  },
  breadcrumb: {
    enabled: true,
    showIcon: true,
    hideOnlyOne: false,
    showHome: true,
    onlyShowHomeIcon: false,
  },
  logo: {
    enable: true,
    source: "/logo.png",
  },
  transition: {
    pageEnter: PageTransitionEnum.SlideLeft,
    progress: true,
    loading: true,
  },
  widget: {
    menuCollapse: true,
    refresh: true,
    search: true,
    fullscreen: true,
    notification: true,
    language: true,
    theme: true,
    lockScreen: true,
    searchIcon: false,
  },
  shortcutKey: {
    enable: true,
    search: true,
    logout: true,
    lockScreen: true,
  },
  router: {
    whiteList: [""],
    routeUseI18n: true,
    nameI18nPrefix: "_route",
    isKeepAlive: false,
    isFull: false,
    cacheDynamicRoutes: false,
    routeUseTooltip: false,
  },
  cache: {
    cacheKeyPrefix: "teek",
    tabNavCacheKey: "tabNav",
    cacheDynamicRoutesKey: "dynamicRoutes",
    versionCacheKey: "version",
    tabExcludesUrlKey: ["layoutMode"],
    cleanCacheWhenUpgrade: false,
  },
} as ServiceConfig;
